services:
  postgres:
    image: postgres:18
    container_name: marvel_postgres_dev
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: marvel
      POSTGRES_PASSWORD: marvel_password
      POSTGRES_DB: marvel_dev
      POSTGRES_INITDB_ARGS: "-U marvel"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marvel -d marvel_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - marvel_network

  redis:
    image: redis:8-alpine
    container_name: marvel_redis_dev
    environment:
      TZ: Asia/Seoul
      REDIS_PASSWORD: marvel_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass marvel_redis_password
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--no-auth-warning",
          "-a",
          "marvel_redis_password",
          "ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - marvel_network

volumes:
  postgres_data:
  redis_data:

networks:
  marvel_network:
    driver: bridge
